FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
	mariadb-server \
	mariadb-client \
	ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

COPY tools/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
COPY conf/50-server.conf /etc/mysql/mariadb.conf.d/50-server.conf

EXPOSE 3306

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]