FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    redis-server ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY conf/redis.conf /etc/redis/redis.conf

EXPOSE 6379
CMD ["redis-server", "/etc/redis/redis.conf"]