listen=YES
listen_ipv6=NO

local_root=/var/www/html
anonymous_enable=NO
local_enable=YES
write_enable=YES

local_umask=022
dirmessage_enable=YES
use_localtime=YES

chroot_local_user=YES
allow_writeable_chroot=YES

pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=127.0.0.1
pasv_addr_resolve=NO

# We will set local_root in entrypoint to /var/www/html